/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class Library {
    /*public boolean someLibraryMethod() {
        return true;
    }
    public static void main(String[] args) {
    	System.out.println(new Library().someLibraryMethod());
    }*/
	public static void main(String[] args) {
		SpringApplication.run(Library.class,args);
		System.out.println("Main class started...Application started");
	}
}
